name: Build & Push

on:
  push:
    branches:
      - test
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Clonar el repo
        uses: actions/checkout@v4

      - name: Loguearse en DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Construir y pushear la imagen
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hugo-novas-gonzalez-daw-web:latest

      - name: Ejecutar el contenedor en localhost:8888
        run: |
          docker run -d -p 8888:80 --name web-container ${{ secrets.DOCKERHUB_USERNAME }}/hugo-novas-gonzalez-daw-web:latest
